ANYARGS	TYPEDEF PROTO :VARARG
PANYARGS TYPEDEF PTR ANYARGS

externdef __imp_$I10_OUTPUT:PANYARGS
vc_$I10_OUTPUT equ <__imp_$I10_OUTPUT>

externdef __imp_??0__non_rtti_object@@QEAA@AEBV0@@Z:PANYARGS
vc_??0__non_rtti_object@@QEAA@AEBV0@@Z equ <__imp_??0__non_rtti_object@@QEAA@AEBV0@@Z>

externdef __imp_??0__non_rtti_object@@QEAA@PEBD@Z:PANYARGS
vc_??0__non_rtti_object@@QEAA@PEBD@Z equ <__imp_??0__non_rtti_object@@QEAA@PEBD@Z>

externdef __imp_??0bad_cast@@AEAA@PEBQEBD@Z:PANYARGS
vc_??0bad_cast@@AEAA@PEBQEBD@Z equ <__imp_??0bad_cast@@AEAA@PEBQEBD@Z>

externdef __imp_??0bad_cast@@QEAA@AEBQEBD@Z:PANYARGS
vc_??0bad_cast@@QEAA@AEBQEBD@Z equ <__imp_??0bad_cast@@QEAA@AEBQEBD@Z>

externdef __imp_??0bad_cast@@QEAA@AEBV0@@Z:PANYARGS
vc_??0bad_cast@@QEAA@AEBV0@@Z equ <__imp_??0bad_cast@@QEAA@AEBV0@@Z>

externdef __imp_??0bad_cast@@QEAA@PEBD@Z:PANYARGS
vc_??0bad_cast@@QEAA@PEBD@Z equ <__imp_??0bad_cast@@QEAA@PEBD@Z>

externdef __imp_??0bad_typeid@@QEAA@AEBV0@@Z:PANYARGS
vc_??0bad_typeid@@QEAA@AEBV0@@Z equ <__imp_??0bad_typeid@@QEAA@AEBV0@@Z>

externdef __imp_??0bad_typeid@@QEAA@PEBD@Z:PANYARGS
vc_??0bad_typeid@@QEAA@PEBD@Z equ <__imp_??0bad_typeid@@QEAA@PEBD@Z>

externdef __imp_??0exception@@QEAA@AEBQEBD@Z:PANYARGS
vc_??0exception@@QEAA@AEBQEBD@Z equ <__imp_??0exception@@QEAA@AEBQEBD@Z>

externdef __imp_??0exception@@QEAA@AEBQEBDH@Z:PANYARGS
vc_??0exception@@QEAA@AEBQEBDH@Z equ <__imp_??0exception@@QEAA@AEBQEBDH@Z>

externdef __imp_??0exception@@QEAA@AEBV0@@Z:PANYARGS
vc_??0exception@@QEAA@AEBV0@@Z equ <__imp_??0exception@@QEAA@AEBV0@@Z>

externdef __imp_??0exception@@QEAA@XZ:PANYARGS
vc_??0exception@@QEAA@XZ equ <__imp_??0exception@@QEAA@XZ>

externdef __imp_??1__non_rtti_object@@UEAA@XZ:PANYARGS
vc_??1__non_rtti_object@@UEAA@XZ equ <__imp_??1__non_rtti_object@@UEAA@XZ>

externdef __imp_??1bad_cast@@UEAA@XZ:PANYARGS
vc_??1bad_cast@@UEAA@XZ equ <__imp_??1bad_cast@@UEAA@XZ>

externdef __imp_??1bad_typeid@@UEAA@XZ:PANYARGS
vc_??1bad_typeid@@UEAA@XZ equ <__imp_??1bad_typeid@@UEAA@XZ>

externdef __imp_??1exception@@UEAA@XZ:PANYARGS
vc_??1exception@@UEAA@XZ equ <__imp_??1exception@@UEAA@XZ>

externdef __imp_??1type_info@@UEAA@XZ:PANYARGS
vc_??1type_info@@UEAA@XZ equ <__imp_??1type_info@@UEAA@XZ>

externdef __imp_??2@YAPEAX_K@Z:PANYARGS
vc_??2@YAPEAX_K@Z equ <__imp_??2@YAPEAX_K@Z>

externdef __imp_??3@YAXPEAX@Z:PANYARGS
vc_??3@YAXPEAX@Z equ <__imp_??3@YAXPEAX@Z>

externdef __imp_??4__non_rtti_object@@QEAAAEAV0@AEBV0@@Z:PANYARGS
vc_??4__non_rtti_object@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4__non_rtti_object@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4bad_cast@@QEAAAEAV0@AEBV0@@Z:PANYARGS
vc_??4bad_cast@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4bad_cast@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4bad_typeid@@QEAAAEAV0@AEBV0@@Z:PANYARGS
vc_??4bad_typeid@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4bad_typeid@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4exception@@QEAAAEAV0@AEBV0@@Z:PANYARGS
vc_??4exception@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4exception@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??8type_info@@QEBAHAEBV0@@Z:PANYARGS
vc_??8type_info@@QEBAHAEBV0@@Z equ <__imp_??8type_info@@QEBAHAEBV0@@Z>

externdef __imp_??9type_info@@QEBAHAEBV0@@Z:PANYARGS
vc_??9type_info@@QEBAHAEBV0@@Z equ <__imp_??9type_info@@QEBAHAEBV0@@Z>

externdef __imp_??_7__non_rtti_object@@6B@:PANYARGS
vc_??_7__non_rtti_object@@6B@ equ <__imp_??_7__non_rtti_object@@6B@>

externdef __imp_??_7bad_cast@@6B@:PANYARGS
vc_??_7bad_cast@@6B@ equ <__imp_??_7bad_cast@@6B@>

externdef __imp_??_7bad_typeid@@6B@:PANYARGS
vc_??_7bad_typeid@@6B@ equ <__imp_??_7bad_typeid@@6B@>

externdef __imp_??_7exception@@6B@:PANYARGS
vc_??_7exception@@6B@ equ <__imp_??_7exception@@6B@>

externdef __imp_??_Fbad_cast@@QEAAXXZ:PANYARGS
vc_??_Fbad_cast@@QEAAXXZ equ <__imp_??_Fbad_cast@@QEAAXXZ>

externdef __imp_??_Fbad_typeid@@QEAAXXZ:PANYARGS
vc_??_Fbad_typeid@@QEAAXXZ equ <__imp_??_Fbad_typeid@@QEAAXXZ>

externdef __imp_??_U@YAPEAX_K@Z:PANYARGS
vc_??_U@YAPEAX_K@Z equ <__imp_??_U@YAPEAX_K@Z>

externdef __imp_??_V@YAXPEAX@Z:PANYARGS
vc_??_V@YAXPEAX@Z equ <__imp_??_V@YAXPEAX@Z>

externdef __imp_?_query_new_handler@@YAP6AH_K@ZXZ:PANYARGS
vc_?_query_new_handler@@YAP6AH_K@ZXZ equ <__imp_?_query_new_handler@@YAP6AH_K@ZXZ>

externdef __imp_?_query_new_mode@@YAHXZ:PANYARGS
vc_?_query_new_mode@@YAHXZ equ <__imp_?_query_new_mode@@YAHXZ>

externdef __imp_?_set_new_handler@@YAP6AH_K@ZP6AH0@Z@Z:PANYARGS
vc_?_set_new_handler@@YAP6AH_K@ZP6AH0@Z@Z equ <__imp_?_set_new_handler@@YAP6AH_K@ZP6AH0@Z@Z>

externdef __imp_?_set_new_mode@@YAHH@Z:PANYARGS
vc_?_set_new_mode@@YAHH@Z equ <__imp_?_set_new_mode@@YAHH@Z>

externdef __imp_?_set_se_translator@@YAP6AXIPEAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z:PANYARGS
vc_?_set_se_translator@@YAP6AXIPEAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z equ <__imp_?_set_se_translator@@YAP6AXIPEAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z>

externdef __imp_?before@type_info@@QEBAHAEBV1@@Z:PANYARGS
vc_?before@type_info@@QEBAHAEBV1@@Z equ <__imp_?before@type_info@@QEBAHAEBV1@@Z>

externdef __imp_?name@type_info@@QEBAPEBDXZ:PANYARGS
vc_?name@type_info@@QEBAPEBDXZ equ <__imp_?name@type_info@@QEBAPEBDXZ>

externdef __imp_?raw_name@type_info@@QEBAPEBDXZ:PANYARGS
vc_?raw_name@type_info@@QEBAPEBDXZ equ <__imp_?raw_name@type_info@@QEBAPEBDXZ>

externdef __imp_?set_new_handler@@YAP6AXXZP6AXXZ@Z:PANYARGS
vc_?set_new_handler@@YAP6AXXZP6AXXZ@Z equ <__imp_?set_new_handler@@YAP6AXXZP6AXXZ@Z>

externdef __imp_?set_terminate@@YAP6AXXZP6AXXZ@Z:PANYARGS
vc_?set_terminate@@YAP6AXXZP6AXXZ@Z equ <__imp_?set_terminate@@YAP6AXXZP6AXXZ@Z>

externdef __imp_?set_unexpected@@YAP6AXXZP6AXXZ@Z:PANYARGS
vc_?set_unexpected@@YAP6AXXZP6AXXZ@Z equ <__imp_?set_unexpected@@YAP6AXXZP6AXXZ@Z>

externdef __imp_?terminate@@YAXXZ:PANYARGS
vc_?terminate@@YAXXZ equ <__imp_?terminate@@YAXXZ>

externdef __imp_?unexpected@@YAXXZ:PANYARGS
vc_?unexpected@@YAXXZ equ <__imp_?unexpected@@YAXXZ>

externdef __imp_?what@exception@@UEBAPEBDXZ:PANYARGS
vc_?what@exception@@UEBAPEBDXZ equ <__imp_?what@exception@@UEBAPEBDXZ>

externdef __imp__CxxThrowException:PANYARGS
vc__CxxThrowException equ <__imp__CxxThrowException>

externdef __imp__Getdays:PANYARGS
vc__Getdays equ <__imp__Getdays>

externdef __imp__Getmonths:PANYARGS
vc__Getmonths equ <__imp__Getmonths>

externdef __imp__Gettnames:PANYARGS
vc__Gettnames equ <__imp__Gettnames>

externdef __imp__HUGE:PANYARGS
vc__HUGE equ <__imp__HUGE>

externdef __imp__Strftime:PANYARGS
vc__Strftime equ <__imp__Strftime>

externdef __imp__XcptFilter:PANYARGS
vc__XcptFilter equ <__imp__XcptFilter>

externdef __imp___C_specific_handler:PANYARGS
vc___C_specific_handler equ <__imp___C_specific_handler>

externdef __imp___CppXcptFilter:PANYARGS
vc___CppXcptFilter equ <__imp___CppXcptFilter>

externdef __imp___CxxFrameHandler:PANYARGS
vc___CxxFrameHandler equ <__imp___CxxFrameHandler>

externdef __imp___DestructExceptionObject:PANYARGS
vc___DestructExceptionObject equ <__imp___DestructExceptionObject>

externdef __imp___RTCastToVoid:PANYARGS
vc___RTCastToVoid equ <__imp___RTCastToVoid>

externdef __imp___RTDynamicCast:PANYARGS
vc___RTDynamicCast equ <__imp___RTDynamicCast>

externdef __imp___RTtypeid:PANYARGS
vc___RTtypeid equ <__imp___RTtypeid>

externdef __imp___STRINGTOLD:PANYARGS
vc___STRINGTOLD equ <__imp___STRINGTOLD>

externdef __imp____lc_codepage_func:PANYARGS
vc____lc_codepage_func equ <__imp____lc_codepage_func>

externdef __imp____lc_collate_cp_func:PANYARGS
vc____lc_collate_cp_func equ <__imp____lc_collate_cp_func>

externdef __imp____lc_handle_func:PANYARGS
vc____lc_handle_func equ <__imp____lc_handle_func>

externdef __imp____mb_cur_max_func:PANYARGS
vc____mb_cur_max_func equ <__imp____mb_cur_max_func>

externdef __imp____setlc_active_func:PANYARGS
vc____setlc_active_func equ <__imp____setlc_active_func>

externdef __imp____unguarded_readlc_active_add_func:PANYARGS
vc____unguarded_readlc_active_add_func equ <__imp____unguarded_readlc_active_add_func>

externdef __imp___argc:PANYARGS
vc___argc equ <__imp___argc>

externdef __imp___argv:PANYARGS
vc___argv equ <__imp___argv>

externdef __imp___badioinfo:PANYARGS
vc___badioinfo equ <__imp___badioinfo>

externdef __imp___crtCompareStringA:PANYARGS
vc___crtCompareStringA equ <__imp___crtCompareStringA>
  IFNDEF __UNICODE__
    __crtCompareString equ <__imp___crtCompareStringA>
  ENDIF

externdef __imp___crtCompareStringW:PANYARGS
vc___crtCompareStringW equ <__imp___crtCompareStringW>
  IFDEF __UNICODE__
    __crtCompareString equ <__imp___crtCompareStringW>
  ENDIF

externdef __imp___crtGetLocaleInfoW:PANYARGS
vc___crtGetLocaleInfoW equ <__imp___crtGetLocaleInfoW>
  IFDEF __UNICODE__
    __crtGetLocaleInfo equ <__imp___crtGetLocaleInfoW>
  ENDIF

externdef __imp___crtGetStringTypeW:PANYARGS
vc___crtGetStringTypeW equ <__imp___crtGetStringTypeW>
  IFDEF __UNICODE__
    __crtGetStringType equ <__imp___crtGetStringTypeW>
  ENDIF

externdef __imp___crtLCMapStringA:PANYARGS
vc___crtLCMapStringA equ <__imp___crtLCMapStringA>
  IFNDEF __UNICODE__
    __crtLCMapString equ <__imp___crtLCMapStringA>
  ENDIF

externdef __imp___crtLCMapStringW:PANYARGS
vc___crtLCMapStringW equ <__imp___crtLCMapStringW>
  IFDEF __UNICODE__
    __crtLCMapString equ <__imp___crtLCMapStringW>
  ENDIF

externdef __imp___dllonexit:PANYARGS
vc___dllonexit equ <__imp___dllonexit>

externdef __imp___doserrno:PANYARGS
vc___doserrno equ <__imp___doserrno>

externdef __imp___fpecode:PANYARGS
vc___fpecode equ <__imp___fpecode>

externdef __imp___getmainargs:PANYARGS
vc___getmainargs equ <__imp___getmainargs>

externdef __imp___initenv:PANYARGS
vc___initenv equ <__imp___initenv>

externdef __imp___iob_func:PANYARGS
vc___iob_func equ <__imp___iob_func>

externdef __imp___isascii:PANYARGS
vc___isascii equ <__imp___isascii>

externdef __imp___iscsym:PANYARGS
vc___iscsym equ <__imp___iscsym>

externdef __imp___iscsymf:PANYARGS
vc___iscsymf equ <__imp___iscsymf>

externdef __imp___lc_codepage:PANYARGS
vc___lc_codepage equ <__imp___lc_codepage>

externdef __imp___lc_collate_cp:PANYARGS
vc___lc_collate_cp equ <__imp___lc_collate_cp>

externdef __imp___lc_handle:PANYARGS
vc___lc_handle equ <__imp___lc_handle>

externdef __imp___lconv_init:PANYARGS
vc___lconv_init equ <__imp___lconv_init>

externdef __imp___mb_cur_max:PANYARGS
vc___mb_cur_max equ <__imp___mb_cur_max>

externdef __imp___pctype_func:PANYARGS
vc___pctype_func equ <__imp___pctype_func>

externdef __imp___pioinfo:PANYARGS
vc___pioinfo equ <__imp___pioinfo>

externdef __imp___pwctype_func:PANYARGS
vc___pwctype_func equ <__imp___pwctype_func>

externdef __imp___pxcptinfoptrs:PANYARGS
vc___pxcptinfoptrs equ <__imp___pxcptinfoptrs>

externdef __imp___set_app_type:PANYARGS
vc___set_app_type equ <__imp___set_app_type>

externdef __imp___setlc_active:PANYARGS
vc___setlc_active equ <__imp___setlc_active>

externdef __imp___setusermatherr:PANYARGS
vc___setusermatherr equ <__imp___setusermatherr>

externdef __imp___threadhandle:PANYARGS
vc___threadhandle equ <__imp___threadhandle>

externdef __imp___threadid:PANYARGS
vc___threadid equ <__imp___threadid>

externdef __imp___toascii:PANYARGS
vc___toascii equ <__imp___toascii>

externdef __imp___unDName:PANYARGS
vc___unDName equ <__imp___unDName>

externdef __imp___unDNameEx:PANYARGS
vc___unDNameEx equ <__imp___unDNameEx>

externdef __imp___uncaught_exception:PANYARGS
vc___uncaught_exception equ <__imp___uncaught_exception>

externdef __imp___unguarded_readlc_active:PANYARGS
vc___unguarded_readlc_active equ <__imp___unguarded_readlc_active>

externdef __imp___wargv:PANYARGS
vc___wargv equ <__imp___wargv>

externdef __imp___wcserror:PANYARGS
vc___wcserror equ <__imp___wcserror>

externdef __imp___wgetmainargs:PANYARGS
vc___wgetmainargs equ <__imp___wgetmainargs>

externdef __imp___winitenv:PANYARGS
vc___winitenv equ <__imp___winitenv>

externdef __imp__abs64:PANYARGS
vc__abs64 equ <__imp__abs64>

externdef __imp__access:PANYARGS
vc__access equ <__imp__access>

externdef __imp__acmdln:PANYARGS
vc__acmdln equ <__imp__acmdln>

externdef __imp__aexit_rtn:PANYARGS
vc__aexit_rtn equ <__imp__aexit_rtn>

externdef __imp__aligned_free:PANYARGS
vc__aligned_free equ <__imp__aligned_free>

externdef __imp__aligned_malloc:PANYARGS
vc__aligned_malloc equ <__imp__aligned_malloc>

externdef __imp__aligned_offset_malloc:PANYARGS
vc__aligned_offset_malloc equ <__imp__aligned_offset_malloc>

externdef __imp__aligned_offset_realloc:PANYARGS
vc__aligned_offset_realloc equ <__imp__aligned_offset_realloc>

externdef __imp__aligned_realloc:PANYARGS
vc__aligned_realloc equ <__imp__aligned_realloc>

externdef __imp__amsg_exit:PANYARGS
vc__amsg_exit equ <__imp__amsg_exit>

externdef __imp__assert:PANYARGS
vc__assert equ <__imp__assert>

externdef __imp__atodbl:PANYARGS
vc__atodbl equ <__imp__atodbl>

externdef __imp__atoi64:PANYARGS
vc__atoi64 equ <__imp__atoi64>

externdef __imp__atoldbl:PANYARGS
vc__atoldbl equ <__imp__atoldbl>

externdef __imp__beep:PANYARGS
vc__beep equ <__imp__beep>

externdef __imp__beginthread:PANYARGS
vc__beginthread equ <__imp__beginthread>

externdef __imp__beginthreadex:PANYARGS
vc__beginthreadex equ <__imp__beginthreadex>

externdef __imp__c_exit:PANYARGS
vc__c_exit equ <__imp__c_exit>

externdef __imp__cabs:PANYARGS
vc__cabs equ <__imp__cabs>

externdef __imp__callnewh:PANYARGS
vc__callnewh equ <__imp__callnewh>

externdef __imp__cexit:PANYARGS
vc__cexit equ <__imp__cexit>

externdef __imp__cgets:PANYARGS
vc__cgets equ <__imp__cgets>

externdef __imp__cgetws:PANYARGS
vc__cgetws equ <__imp__cgetws>

externdef __imp__chdir:PANYARGS
vc__chdir equ <__imp__chdir>

externdef __imp__chdrive:PANYARGS
vc__chdrive equ <__imp__chdrive>

externdef __imp__chgsign:PANYARGS
vc__chgsign equ <__imp__chgsign>

externdef __imp__chgsignf:PANYARGS
vc__chgsignf equ <__imp__chgsignf>

externdef __imp__chmod:PANYARGS
vc__chmod equ <__imp__chmod>

externdef __imp__chsize:PANYARGS
vc__chsize equ <__imp__chsize>

externdef __imp__clearfp:PANYARGS
vc__clearfp equ <__imp__clearfp>

externdef __imp__close:PANYARGS
vc__close equ <__imp__close>

externdef __imp__commit:PANYARGS
vc__commit equ <__imp__commit>

externdef __imp__commode:PANYARGS
vc__commode equ <__imp__commode>

externdef __imp__control87:PANYARGS
vc__control87 equ <__imp__control87>

externdef __imp__controlfp:PANYARGS
vc__controlfp equ <__imp__controlfp>

externdef __imp__copysign:PANYARGS
vc__copysign equ <__imp__copysign>

externdef __imp__copysignf:PANYARGS
vc__copysignf equ <__imp__copysignf>

externdef __imp__cprintf:PANYARGS
vc__cprintf equ <__imp__cprintf>

externdef __imp__cputs:PANYARGS
vc__cputs equ <__imp__cputs>

externdef __imp__cputws:PANYARGS
vc__cputws equ <__imp__cputws>

externdef __imp__creat:PANYARGS
vc__creat equ <__imp__creat>

externdef __imp__cscanf:PANYARGS
vc__cscanf equ <__imp__cscanf>

externdef __imp__ctime64:PANYARGS
vc__ctime64 equ <__imp__ctime64>

externdef __imp__ctype:PANYARGS
vc__ctype equ <__imp__ctype>

externdef __imp__cwait:PANYARGS
vc__cwait equ <__imp__cwait>

externdef __imp__cwprintf:PANYARGS
vc__cwprintf equ <__imp__cwprintf>

externdef __imp__cwscanf:PANYARGS
vc__cwscanf equ <__imp__cwscanf>

externdef __imp__daylight:PANYARGS
vc__daylight equ <__imp__daylight>

externdef __imp__dstbias:PANYARGS
vc__dstbias equ <__imp__dstbias>

externdef __imp__dup2:PANYARGS
vc__dup2 equ <__imp__dup2>

externdef __imp__dup:PANYARGS
vc__dup equ <__imp__dup>

externdef __imp__ecvt:PANYARGS
vc__ecvt equ <__imp__ecvt>

externdef __imp__endthread:PANYARGS
vc__endthread equ <__imp__endthread>

externdef __imp__endthreadex:PANYARGS
vc__endthreadex equ <__imp__endthreadex>

externdef __imp__environ:PANYARGS
vc__environ equ <__imp__environ>

externdef __imp__eof:PANYARGS
vc__eof equ <__imp__eof>

externdef __imp__errno:PANYARGS
vc__errno equ <__imp__errno>

externdef __imp__execl:PANYARGS
vc__execl equ <__imp__execl>

externdef __imp__execle:PANYARGS
vc__execle equ <__imp__execle>

externdef __imp__execlp:PANYARGS
vc__execlp equ <__imp__execlp>

externdef __imp__execlpe:PANYARGS
vc__execlpe equ <__imp__execlpe>

externdef __imp__execv:PANYARGS
vc__execv equ <__imp__execv>

externdef __imp__execve:PANYARGS
vc__execve equ <__imp__execve>

externdef __imp__execvp:PANYARGS
vc__execvp equ <__imp__execvp>

externdef __imp__execvpe:PANYARGS
vc__execvpe equ <__imp__execvpe>

externdef __imp__exit:PANYARGS
vc__exit equ <__imp__exit>

externdef __imp__expand:PANYARGS
vc__expand equ <__imp__expand>

externdef __imp__fcloseall:PANYARGS
vc__fcloseall equ <__imp__fcloseall>

externdef __imp__fcvt:PANYARGS
vc__fcvt equ <__imp__fcvt>

externdef __imp__fdopen:PANYARGS
vc__fdopen equ <__imp__fdopen>

externdef __imp__fgetchar:PANYARGS
vc__fgetchar equ <__imp__fgetchar>

externdef __imp__fgetwchar:PANYARGS
vc__fgetwchar equ <__imp__fgetwchar>

externdef __imp__filbuf:PANYARGS
vc__filbuf equ <__imp__filbuf>

externdef __imp__fileinfo:PANYARGS
vc__fileinfo equ <__imp__fileinfo>

externdef __imp__filelength:PANYARGS
vc__filelength equ <__imp__filelength>

externdef __imp__filelengthi64:PANYARGS
vc__filelengthi64 equ <__imp__filelengthi64>

externdef __imp__fileno:PANYARGS
vc__fileno equ <__imp__fileno>

externdef __imp__findclose:PANYARGS
vc__findclose equ <__imp__findclose>

externdef __imp__findfirst64:PANYARGS
vc__findfirst64 equ <__imp__findfirst64>

externdef __imp__findfirst:PANYARGS
vc__findfirst equ <__imp__findfirst>

externdef __imp__findfirsti64:PANYARGS
vc__findfirsti64 equ <__imp__findfirsti64>

externdef __imp__findnext64:PANYARGS
vc__findnext64 equ <__imp__findnext64>

externdef __imp__findnext:PANYARGS
vc__findnext equ <__imp__findnext>

externdef __imp__findnexti64:PANYARGS
vc__findnexti64 equ <__imp__findnexti64>

externdef __imp__finite:PANYARGS
vc__finite equ <__imp__finite>

externdef __imp__finitef:PANYARGS
vc__finitef equ <__imp__finitef>

externdef __imp__flsbuf:PANYARGS
vc__flsbuf equ <__imp__flsbuf>

externdef __imp__flushall:PANYARGS
vc__flushall equ <__imp__flushall>

externdef __imp__fmode:PANYARGS
vc__fmode equ <__imp__fmode>

externdef __imp__fpclass:PANYARGS
vc__fpclass equ <__imp__fpclass>

externdef __imp__fpclassf:PANYARGS
vc__fpclassf equ <__imp__fpclassf>

externdef __imp__fpreset:PANYARGS
vc__fpreset equ <__imp__fpreset>

externdef __imp__fputchar:PANYARGS
vc__fputchar equ <__imp__fputchar>

externdef __imp__fputwchar:PANYARGS
vc__fputwchar equ <__imp__fputwchar>

externdef __imp__fsopen:PANYARGS
vc__fsopen equ <__imp__fsopen>

externdef __imp__fstat64:PANYARGS
vc__fstat64 equ <__imp__fstat64>

externdef __imp__fstat:PANYARGS
vc__fstat equ <__imp__fstat>

externdef __imp__fstati64:PANYARGS
vc__fstati64 equ <__imp__fstati64>

externdef __imp__ftime64:PANYARGS
vc__ftime64 equ <__imp__ftime64>

externdef __imp__ftime:PANYARGS
vc__ftime equ <__imp__ftime>

externdef __imp__fullpath:PANYARGS
vc__fullpath equ <__imp__fullpath>

externdef __imp__futime64:PANYARGS
vc__futime64 equ <__imp__futime64>

externdef __imp__futime:PANYARGS
vc__futime equ <__imp__futime>

externdef __imp__gcvt:PANYARGS
vc__gcvt equ <__imp__gcvt>

externdef __imp__get_heap_handle:PANYARGS
vc__get_heap_handle equ <__imp__get_heap_handle>

externdef __imp__get_osfhandle:PANYARGS
vc__get_osfhandle equ <__imp__get_osfhandle>

externdef __imp__get_sbh_threshold:PANYARGS
vc__get_sbh_threshold equ <__imp__get_sbh_threshold>

externdef __imp__getch:PANYARGS
vc__getch equ <__imp__getch>

externdef __imp__getche:PANYARGS
vc__getche equ <__imp__getche>

externdef __imp__getcwd:PANYARGS
vc__getcwd equ <__imp__getcwd>

externdef __imp__getdcwd:PANYARGS
vc__getdcwd equ <__imp__getdcwd>

externdef __imp__getdiskfree:PANYARGS
vc__getdiskfree equ <__imp__getdiskfree>

externdef __imp__getdllprocaddr:PANYARGS
vc__getdllprocaddr equ <__imp__getdllprocaddr>

externdef __imp__getdrive:PANYARGS
vc__getdrive equ <__imp__getdrive>

externdef __imp__getdrives:PANYARGS
vc__getdrives equ <__imp__getdrives>

externdef __imp__getmaxstdio:PANYARGS
vc__getmaxstdio equ <__imp__getmaxstdio>

externdef __imp__getmbcp:PANYARGS
vc__getmbcp equ <__imp__getmbcp>

externdef __imp__getpid:PANYARGS
vc__getpid equ <__imp__getpid>

externdef __imp__getsystime:PANYARGS
vc__getsystime equ <__imp__getsystime>

externdef __imp__getw:PANYARGS
vc__getw equ <__imp__getw>

externdef __imp__getwch:PANYARGS
vc__getwch equ <__imp__getwch>

externdef __imp__getwche:PANYARGS
vc__getwche equ <__imp__getwche>

externdef __imp__getws:PANYARGS
vc__getws equ <__imp__getws>

externdef __imp__gmtime64:PANYARGS
vc__gmtime64 equ <__imp__gmtime64>

externdef __imp__heapadd:PANYARGS
vc__heapadd equ <__imp__heapadd>

externdef __imp__heapchk:PANYARGS
vc__heapchk equ <__imp__heapchk>

externdef __imp__heapmin:PANYARGS
vc__heapmin equ <__imp__heapmin>

externdef __imp__heapset:PANYARGS
vc__heapset equ <__imp__heapset>

externdef __imp__heapused:PANYARGS
vc__heapused equ <__imp__heapused>

externdef __imp__heapwalk:PANYARGS
vc__heapwalk equ <__imp__heapwalk>

externdef __imp__hypot:PANYARGS
vc__hypot equ <__imp__hypot>

externdef __imp__hypotf:PANYARGS
vc__hypotf equ <__imp__hypotf>

externdef __imp__i64toa:PANYARGS
vc__i64toa equ <__imp__i64toa>

externdef __imp__i64tow:PANYARGS
vc__i64tow equ <__imp__i64tow>

externdef __imp__initterm:PANYARGS
vc__initterm equ <__imp__initterm>

externdef __imp__iob:PANYARGS
vc__iob equ <__imp__iob>

externdef __imp__isatty:PANYARGS
vc__isatty equ <__imp__isatty>

externdef __imp__isctype:PANYARGS
vc__isctype equ <__imp__isctype>

externdef __imp__ismbbalnum:PANYARGS
vc__ismbbalnum equ <__imp__ismbbalnum>

externdef __imp__ismbbalpha:PANYARGS
vc__ismbbalpha equ <__imp__ismbbalpha>

externdef __imp__ismbbgraph:PANYARGS
vc__ismbbgraph equ <__imp__ismbbgraph>

externdef __imp__ismbbkalnum:PANYARGS
vc__ismbbkalnum equ <__imp__ismbbkalnum>

externdef __imp__ismbbkana:PANYARGS
vc__ismbbkana equ <__imp__ismbbkana>

externdef __imp__ismbbkprint:PANYARGS
vc__ismbbkprint equ <__imp__ismbbkprint>

externdef __imp__ismbbkpunct:PANYARGS
vc__ismbbkpunct equ <__imp__ismbbkpunct>

externdef __imp__ismbblead:PANYARGS
vc__ismbblead equ <__imp__ismbblead>

externdef __imp__ismbbprint:PANYARGS
vc__ismbbprint equ <__imp__ismbbprint>

externdef __imp__ismbbpunct:PANYARGS
vc__ismbbpunct equ <__imp__ismbbpunct>

externdef __imp__ismbbtrail:PANYARGS
vc__ismbbtrail equ <__imp__ismbbtrail>

externdef __imp__ismbcalnum:PANYARGS
vc__ismbcalnum equ <__imp__ismbcalnum>

externdef __imp__ismbcalpha:PANYARGS
vc__ismbcalpha equ <__imp__ismbcalpha>

externdef __imp__ismbcdigit:PANYARGS
vc__ismbcdigit equ <__imp__ismbcdigit>

externdef __imp__ismbcgraph:PANYARGS
vc__ismbcgraph equ <__imp__ismbcgraph>

externdef __imp__ismbchira:PANYARGS
vc__ismbchira equ <__imp__ismbchira>

externdef __imp__ismbckata:PANYARGS
vc__ismbckata equ <__imp__ismbckata>

externdef __imp__ismbcl0:PANYARGS
vc__ismbcl0 equ <__imp__ismbcl0>

externdef __imp__ismbcl1:PANYARGS
vc__ismbcl1 equ <__imp__ismbcl1>

externdef __imp__ismbcl2:PANYARGS
vc__ismbcl2 equ <__imp__ismbcl2>

externdef __imp__ismbclegal:PANYARGS
vc__ismbclegal equ <__imp__ismbclegal>

externdef __imp__ismbclower:PANYARGS
vc__ismbclower equ <__imp__ismbclower>

externdef __imp__ismbcprint:PANYARGS
vc__ismbcprint equ <__imp__ismbcprint>

externdef __imp__ismbcpunct:PANYARGS
vc__ismbcpunct equ <__imp__ismbcpunct>

externdef __imp__ismbcspace:PANYARGS
vc__ismbcspace equ <__imp__ismbcspace>

externdef __imp__ismbcsymbol:PANYARGS
vc__ismbcsymbol equ <__imp__ismbcsymbol>

externdef __imp__ismbcupper:PANYARGS
vc__ismbcupper equ <__imp__ismbcupper>

externdef __imp__ismbslead:PANYARGS
vc__ismbslead equ <__imp__ismbslead>

externdef __imp__ismbstrail:PANYARGS
vc__ismbstrail equ <__imp__ismbstrail>

externdef __imp__isnan:PANYARGS
vc__isnan equ <__imp__isnan>

externdef __imp__isnanf:PANYARGS
vc__isnanf equ <__imp__isnanf>

externdef __imp__itoa:PANYARGS
vc__itoa equ <__imp__itoa>

externdef __imp__itow:PANYARGS
vc__itow equ <__imp__itow>

externdef __imp__j0:PANYARGS
vc__j0 equ <__imp__j0>

externdef __imp__j1:PANYARGS
vc__j1 equ <__imp__j1>

externdef __imp__jn:PANYARGS
vc__jn equ <__imp__jn>

externdef __imp__kbhit:PANYARGS
vc__kbhit equ <__imp__kbhit>

externdef __imp__lfind:PANYARGS
vc__lfind equ <__imp__lfind>

externdef __imp__loaddll:PANYARGS
vc__loaddll equ <__imp__loaddll>

externdef __imp__local_unwind:PANYARGS
vc__local_unwind equ <__imp__local_unwind>

externdef __imp__localtime64:PANYARGS
vc__localtime64 equ <__imp__localtime64>

externdef __imp__lock:PANYARGS
vc__lock equ <__imp__lock>

externdef __imp__locking:PANYARGS
vc__locking equ <__imp__locking>

externdef __imp__logb:PANYARGS
vc__logb equ <__imp__logb>

externdef __imp__logbf:PANYARGS
vc__logbf equ <__imp__logbf>

externdef __imp__lrotl:PANYARGS
vc__lrotl equ <__imp__lrotl>

externdef __imp__lrotr:PANYARGS
vc__lrotr equ <__imp__lrotr>

externdef __imp__lsearch:PANYARGS
vc__lsearch equ <__imp__lsearch>

externdef __imp__lseek:PANYARGS
vc__lseek equ <__imp__lseek>

externdef __imp__lseeki64:PANYARGS
vc__lseeki64 equ <__imp__lseeki64>

externdef __imp__ltoa:PANYARGS
vc__ltoa equ <__imp__ltoa>

externdef __imp__ltow:PANYARGS
vc__ltow equ <__imp__ltow>

externdef __imp__makepath:PANYARGS
vc__makepath equ <__imp__makepath>

externdef __imp__mbbtombc:PANYARGS
vc__mbbtombc equ <__imp__mbbtombc>

externdef __imp__mbbtype:PANYARGS
vc__mbbtype equ <__imp__mbbtype>

externdef __imp__mbcasemap:PANYARGS
vc__mbcasemap equ <__imp__mbcasemap>

externdef __imp__mbccpy:PANYARGS
vc__mbccpy equ <__imp__mbccpy>

externdef __imp__mbcjistojms:PANYARGS
vc__mbcjistojms equ <__imp__mbcjistojms>

externdef __imp__mbcjmstojis:PANYARGS
vc__mbcjmstojis equ <__imp__mbcjmstojis>

externdef __imp__mbclen:PANYARGS
vc__mbclen equ <__imp__mbclen>

externdef __imp__mbctohira:PANYARGS
vc__mbctohira equ <__imp__mbctohira>

externdef __imp__mbctokata:PANYARGS
vc__mbctokata equ <__imp__mbctokata>

externdef __imp__mbctolower:PANYARGS
vc__mbctolower equ <__imp__mbctolower>

externdef __imp__mbctombb:PANYARGS
vc__mbctombb equ <__imp__mbctombb>

externdef __imp__mbctoupper:PANYARGS
vc__mbctoupper equ <__imp__mbctoupper>

externdef __imp__mbctype:PANYARGS
vc__mbctype equ <__imp__mbctype>

externdef __imp__mbsbtype:PANYARGS
vc__mbsbtype equ <__imp__mbsbtype>

externdef __imp__mbscat:PANYARGS
vc__mbscat equ <__imp__mbscat>

externdef __imp__mbschr:PANYARGS
vc__mbschr equ <__imp__mbschr>

externdef __imp__mbscmp:PANYARGS
vc__mbscmp equ <__imp__mbscmp>

externdef __imp__mbscoll:PANYARGS
vc__mbscoll equ <__imp__mbscoll>

externdef __imp__mbscpy:PANYARGS
vc__mbscpy equ <__imp__mbscpy>

externdef __imp__mbscspn:PANYARGS
vc__mbscspn equ <__imp__mbscspn>

externdef __imp__mbsdec:PANYARGS
vc__mbsdec equ <__imp__mbsdec>

externdef __imp__mbsdup:PANYARGS
vc__mbsdup equ <__imp__mbsdup>

externdef __imp__mbsicmp:PANYARGS
vc__mbsicmp equ <__imp__mbsicmp>

externdef __imp__mbsicoll:PANYARGS
vc__mbsicoll equ <__imp__mbsicoll>

externdef __imp__mbsinc:PANYARGS
vc__mbsinc equ <__imp__mbsinc>

externdef __imp__mbslen:PANYARGS
vc__mbslen equ <__imp__mbslen>

externdef __imp__mbslwr:PANYARGS
vc__mbslwr equ <__imp__mbslwr>

externdef __imp__mbsnbcat:PANYARGS
vc__mbsnbcat equ <__imp__mbsnbcat>

externdef __imp__mbsnbcmp:PANYARGS
vc__mbsnbcmp equ <__imp__mbsnbcmp>

externdef __imp__mbsnbcnt:PANYARGS
vc__mbsnbcnt equ <__imp__mbsnbcnt>

externdef __imp__mbsnbcoll:PANYARGS
vc__mbsnbcoll equ <__imp__mbsnbcoll>

externdef __imp__mbsnbcpy:PANYARGS
vc__mbsnbcpy equ <__imp__mbsnbcpy>

externdef __imp__mbsnbicmp:PANYARGS
vc__mbsnbicmp equ <__imp__mbsnbicmp>

externdef __imp__mbsnbicoll:PANYARGS
vc__mbsnbicoll equ <__imp__mbsnbicoll>

externdef __imp__mbsnbset:PANYARGS
vc__mbsnbset equ <__imp__mbsnbset>

externdef __imp__mbsncat:PANYARGS
vc__mbsncat equ <__imp__mbsncat>

externdef __imp__mbsnccnt:PANYARGS
vc__mbsnccnt equ <__imp__mbsnccnt>

externdef __imp__mbsncmp:PANYARGS
vc__mbsncmp equ <__imp__mbsncmp>

externdef __imp__mbsncoll:PANYARGS
vc__mbsncoll equ <__imp__mbsncoll>

externdef __imp__mbsncpy:PANYARGS
vc__mbsncpy equ <__imp__mbsncpy>

externdef __imp__mbsnextc:PANYARGS
vc__mbsnextc equ <__imp__mbsnextc>

externdef __imp__mbsnicmp:PANYARGS
vc__mbsnicmp equ <__imp__mbsnicmp>

externdef __imp__mbsnicoll:PANYARGS
vc__mbsnicoll equ <__imp__mbsnicoll>

externdef __imp__mbsninc:PANYARGS
vc__mbsninc equ <__imp__mbsninc>

externdef __imp__mbsnset:PANYARGS
vc__mbsnset equ <__imp__mbsnset>

externdef __imp__mbspbrk:PANYARGS
vc__mbspbrk equ <__imp__mbspbrk>

externdef __imp__mbsrchr:PANYARGS
vc__mbsrchr equ <__imp__mbsrchr>

externdef __imp__mbsrev:PANYARGS
vc__mbsrev equ <__imp__mbsrev>

externdef __imp__mbsset:PANYARGS
vc__mbsset equ <__imp__mbsset>

externdef __imp__mbsspn:PANYARGS
vc__mbsspn equ <__imp__mbsspn>

externdef __imp__mbsspnp:PANYARGS
vc__mbsspnp equ <__imp__mbsspnp>

externdef __imp__mbsstr:PANYARGS
vc__mbsstr equ <__imp__mbsstr>

externdef __imp__mbstok:PANYARGS
vc__mbstok equ <__imp__mbstok>

externdef __imp__mbstrlen:PANYARGS
vc__mbstrlen equ <__imp__mbstrlen>

externdef __imp__mbsupr:PANYARGS
vc__mbsupr equ <__imp__mbsupr>

externdef __imp__memccpy:PANYARGS
vc__memccpy equ <__imp__memccpy>

externdef __imp__memicmp:PANYARGS
vc__memicmp equ <__imp__memicmp>

externdef __imp__mkdir:PANYARGS
vc__mkdir equ <__imp__mkdir>

externdef __imp__mkgmtime64:PANYARGS
vc__mkgmtime64 equ <__imp__mkgmtime64>

externdef __imp__mkgmtime:PANYARGS
vc__mkgmtime equ <__imp__mkgmtime>

externdef __imp__mktemp:PANYARGS
vc__mktemp equ <__imp__mktemp>

externdef __imp__mktime64:PANYARGS
vc__mktime64 equ <__imp__mktime64>

externdef __imp__msize:PANYARGS
vc__msize equ <__imp__msize>

externdef __imp__nextafter:PANYARGS
vc__nextafter equ <__imp__nextafter>

externdef __imp__nextafterf:PANYARGS
vc__nextafterf equ <__imp__nextafterf>

externdef __imp__onexit:PANYARGS
vc__onexit equ <__imp__onexit>

externdef __imp__open:PANYARGS
vc__open equ <__imp__open>

externdef __imp__open_osfhandle:PANYARGS
vc__open_osfhandle equ <__imp__open_osfhandle>

externdef __imp__osplatform:PANYARGS
vc__osplatform equ <__imp__osplatform>

externdef __imp__osver:PANYARGS
vc__osver equ <__imp__osver>

externdef __imp__pclose:PANYARGS
vc__pclose equ <__imp__pclose>

externdef __imp__pctype:PANYARGS
vc__pctype equ <__imp__pctype>

externdef __imp__pgmptr:PANYARGS
vc__pgmptr equ <__imp__pgmptr>

externdef __imp__pipe:PANYARGS
vc__pipe equ <__imp__pipe>

externdef __imp__popen:PANYARGS
vc__popen equ <__imp__popen>

externdef __imp__purecall:PANYARGS
vc__purecall equ <__imp__purecall>

externdef __imp__putch:PANYARGS
vc__putch equ <__imp__putch>

externdef __imp__putenv:PANYARGS
vc__putenv equ <__imp__putenv>

externdef __imp__putw:PANYARGS
vc__putw equ <__imp__putw>

externdef __imp__putwch:PANYARGS
vc__putwch equ <__imp__putwch>

externdef __imp__putws:PANYARGS
vc__putws equ <__imp__putws>

externdef __imp__pwctype:PANYARGS
vc__pwctype equ <__imp__pwctype>

externdef __imp__read:PANYARGS
vc__read equ <__imp__read>

externdef __imp__resetstkoflw:PANYARGS
vc__resetstkoflw equ <__imp__resetstkoflw>

externdef __imp__rmdir:PANYARGS
vc__rmdir equ <__imp__rmdir>

externdef __imp__rmtmp:PANYARGS
vc__rmtmp equ <__imp__rmtmp>

externdef __imp__rotl64:PANYARGS
vc__rotl64 equ <__imp__rotl64>

externdef __imp__rotl:PANYARGS
vc__rotl equ <__imp__rotl>

externdef __imp__rotr64:PANYARGS
vc__rotr64 equ <__imp__rotr64>

externdef __imp__rotr:PANYARGS
vc__rotr equ <__imp__rotr>

externdef __imp__scalb:PANYARGS
vc__scalb equ <__imp__scalb>

externdef __imp__scalbf:PANYARGS
vc__scalbf equ <__imp__scalbf>

externdef __imp__scprintf:PANYARGS
vc__scprintf equ <__imp__scprintf>

externdef __imp__scwprintf:PANYARGS
vc__scwprintf equ <__imp__scwprintf>

externdef __imp__searchenv:PANYARGS
vc__searchenv equ <__imp__searchenv>

externdef __imp__set_error_mode:PANYARGS
vc__set_error_mode equ <__imp__set_error_mode>

externdef __imp__set_sbh_threshold:PANYARGS
vc__set_sbh_threshold equ <__imp__set_sbh_threshold>

externdef __imp__seterrormode:PANYARGS
vc__seterrormode equ <__imp__seterrormode>

externdef __imp__setjmp:PANYARGS
vc__setjmp equ <__imp__setjmp>

externdef __imp__setjmpex:PANYARGS
vc__setjmpex equ <__imp__setjmpex>

externdef __imp__setmaxstdio:PANYARGS
vc__setmaxstdio equ <__imp__setmaxstdio>

externdef __imp__setmbcp:PANYARGS
vc__setmbcp equ <__imp__setmbcp>

externdef __imp__setmode:PANYARGS
vc__setmode equ <__imp__setmode>

externdef __imp__setsystime:PANYARGS
vc__setsystime equ <__imp__setsystime>

externdef __imp__sleep:PANYARGS
vc__sleep equ <__imp__sleep>

externdef __imp__snprintf:PANYARGS
vc__snprintf equ <__imp__snprintf>

externdef __imp__snscanf:PANYARGS
vc__snscanf equ <__imp__snscanf>

externdef __imp__snwprintf:PANYARGS
vc__snwprintf equ <__imp__snwprintf>

externdef __imp__snwscanf:PANYARGS
vc__snwscanf equ <__imp__snwscanf>

externdef __imp__sopen:PANYARGS
vc__sopen equ <__imp__sopen>

externdef __imp__spawnl:PANYARGS
vc__spawnl equ <__imp__spawnl>

externdef __imp__spawnle:PANYARGS
vc__spawnle equ <__imp__spawnle>

externdef __imp__spawnlp:PANYARGS
vc__spawnlp equ <__imp__spawnlp>

externdef __imp__spawnlpe:PANYARGS
vc__spawnlpe equ <__imp__spawnlpe>

externdef __imp__spawnv:PANYARGS
vc__spawnv equ <__imp__spawnv>

externdef __imp__spawnve:PANYARGS
vc__spawnve equ <__imp__spawnve>

externdef __imp__spawnvp:PANYARGS
vc__spawnvp equ <__imp__spawnvp>

externdef __imp__spawnvpe:PANYARGS
vc__spawnvpe equ <__imp__spawnvpe>

externdef __imp__splitpath:PANYARGS
vc__splitpath equ <__imp__splitpath>

externdef __imp__stat64:PANYARGS
vc__stat64 equ <__imp__stat64>

externdef __imp__stat:PANYARGS
vc__stat equ <__imp__stat>

externdef __imp__stati64:PANYARGS
vc__stati64 equ <__imp__stati64>

externdef __imp__statusfp:PANYARGS
vc__statusfp equ <__imp__statusfp>

externdef __imp__strcmpi:PANYARGS
vc__strcmpi equ <__imp__strcmpi>

externdef __imp__strdate:PANYARGS
vc__strdate equ <__imp__strdate>

externdef __imp__strdup:PANYARGS
vc__strdup equ <__imp__strdup>

externdef __imp__strerror:PANYARGS
vc__strerror equ <__imp__strerror>

externdef __imp__stricmp:PANYARGS
vc__stricmp equ <__imp__stricmp>

externdef __imp__stricoll:PANYARGS
vc__stricoll equ <__imp__stricoll>

externdef __imp__strlwr:PANYARGS
vc__strlwr equ <__imp__strlwr>

externdef __imp__strncoll:PANYARGS
vc__strncoll equ <__imp__strncoll>

externdef __imp__strnicmp:PANYARGS
vc__strnicmp equ <__imp__strnicmp>

externdef __imp__strnicoll:PANYARGS
vc__strnicoll equ <__imp__strnicoll>

externdef __imp__strnset:PANYARGS
vc__strnset equ <__imp__strnset>

externdef __imp__strrev:PANYARGS
vc__strrev equ <__imp__strrev>

externdef __imp__strset:PANYARGS
vc__strset equ <__imp__strset>

externdef __imp__strtime:PANYARGS
vc__strtime equ <__imp__strtime>

externdef __imp__strtoi64:PANYARGS
vc__strtoi64 equ <__imp__strtoi64>

externdef __imp__strtoui64:PANYARGS
vc__strtoui64 equ <__imp__strtoui64>

externdef __imp__strupr:PANYARGS
vc__strupr equ <__imp__strupr>

externdef __imp__swab:PANYARGS
vc__swab equ <__imp__swab>

externdef __imp__sys_errlist:PANYARGS
vc__sys_errlist equ <__imp__sys_errlist>

externdef __imp__sys_nerr:PANYARGS
vc__sys_nerr equ <__imp__sys_nerr>

externdef __imp__tell:PANYARGS
vc__tell equ <__imp__tell>

externdef __imp__telli64:PANYARGS
vc__telli64 equ <__imp__telli64>

externdef __imp__tempnam:PANYARGS
vc__tempnam equ <__imp__tempnam>

externdef __imp__time64:PANYARGS
vc__time64 equ <__imp__time64>

externdef __imp__timezone:PANYARGS
vc__timezone equ <__imp__timezone>

externdef __imp__tolower:PANYARGS
vc__tolower equ <__imp__tolower>

externdef __imp__toupper:PANYARGS
vc__toupper equ <__imp__toupper>

externdef __imp__tzname:PANYARGS
vc__tzname equ <__imp__tzname>

externdef __imp__tzset:PANYARGS
vc__tzset equ <__imp__tzset>

externdef __imp__ui64toa:PANYARGS
vc__ui64toa equ <__imp__ui64toa>

externdef __imp__ui64tow:PANYARGS
vc__ui64tow equ <__imp__ui64tow>

externdef __imp__ultoa:PANYARGS
vc__ultoa equ <__imp__ultoa>

externdef __imp__ultow:PANYARGS
vc__ultow equ <__imp__ultow>

externdef __imp__umask:PANYARGS
vc__umask equ <__imp__umask>

externdef __imp__ungetch:PANYARGS
vc__ungetch equ <__imp__ungetch>

externdef __imp__ungetwch:PANYARGS
vc__ungetwch equ <__imp__ungetwch>

externdef __imp__unlink:PANYARGS
vc__unlink equ <__imp__unlink>

externdef __imp__unloaddll:PANYARGS
vc__unloaddll equ <__imp__unloaddll>

externdef __imp__unlock:PANYARGS
vc__unlock equ <__imp__unlock>

externdef __imp__utime64:PANYARGS
vc__utime64 equ <__imp__utime64>

externdef __imp__utime:PANYARGS
vc__utime equ <__imp__utime>

externdef __imp__vscprintf:PANYARGS
vc__vscprintf equ <__imp__vscprintf>

externdef __imp__vscwprintf:PANYARGS
vc__vscwprintf equ <__imp__vscwprintf>

externdef __imp__vsnprintf:PANYARGS
vc__vsnprintf equ <__imp__vsnprintf>

externdef __imp__vsnwprintf:PANYARGS
vc__vsnwprintf equ <__imp__vsnwprintf>

externdef __imp__waccess:PANYARGS
vc__waccess equ <__imp__waccess>

externdef __imp__wasctime:PANYARGS
vc__wasctime equ <__imp__wasctime>

externdef __imp__wchdir:PANYARGS
vc__wchdir equ <__imp__wchdir>

externdef __imp__wchmod:PANYARGS
vc__wchmod equ <__imp__wchmod>

externdef __imp__wcmdln:PANYARGS
vc__wcmdln equ <__imp__wcmdln>

externdef __imp__wcreat:PANYARGS
vc__wcreat equ <__imp__wcreat>

externdef __imp__wcsdup:PANYARGS
vc__wcsdup equ <__imp__wcsdup>

externdef __imp__wcserror:PANYARGS
vc__wcserror equ <__imp__wcserror>

externdef __imp__wcsicmp:PANYARGS
vc__wcsicmp equ <__imp__wcsicmp>

externdef __imp__wcsicoll:PANYARGS
vc__wcsicoll equ <__imp__wcsicoll>

externdef __imp__wcslwr:PANYARGS
vc__wcslwr equ <__imp__wcslwr>

externdef __imp__wcsncoll:PANYARGS
vc__wcsncoll equ <__imp__wcsncoll>

externdef __imp__wcsnicmp:PANYARGS
vc__wcsnicmp equ <__imp__wcsnicmp>

externdef __imp__wcsnicoll:PANYARGS
vc__wcsnicoll equ <__imp__wcsnicoll>

externdef __imp__wcsnset:PANYARGS
vc__wcsnset equ <__imp__wcsnset>

externdef __imp__wcsrev:PANYARGS
vc__wcsrev equ <__imp__wcsrev>

externdef __imp__wcsset:PANYARGS
vc__wcsset equ <__imp__wcsset>

externdef __imp__wcstoi64:PANYARGS
vc__wcstoi64 equ <__imp__wcstoi64>

externdef __imp__wcstoui64:PANYARGS
vc__wcstoui64 equ <__imp__wcstoui64>

externdef __imp__wcsupr:PANYARGS
vc__wcsupr equ <__imp__wcsupr>

externdef __imp__wctime64:PANYARGS
vc__wctime64 equ <__imp__wctime64>

externdef __imp__wctime:PANYARGS
vc__wctime equ <__imp__wctime>

externdef __imp__wctype:PANYARGS
vc__wctype equ <__imp__wctype>

externdef __imp__wenviron:PANYARGS
vc__wenviron equ <__imp__wenviron>

externdef __imp__wexecl:PANYARGS
vc__wexecl equ <__imp__wexecl>

externdef __imp__wexecle:PANYARGS
vc__wexecle equ <__imp__wexecle>

externdef __imp__wexeclp:PANYARGS
vc__wexeclp equ <__imp__wexeclp>

externdef __imp__wexeclpe:PANYARGS
vc__wexeclpe equ <__imp__wexeclpe>

externdef __imp__wexecv:PANYARGS
vc__wexecv equ <__imp__wexecv>

externdef __imp__wexecve:PANYARGS
vc__wexecve equ <__imp__wexecve>

externdef __imp__wexecvp:PANYARGS
vc__wexecvp equ <__imp__wexecvp>

externdef __imp__wexecvpe:PANYARGS
vc__wexecvpe equ <__imp__wexecvpe>

externdef __imp__wfdopen:PANYARGS
vc__wfdopen equ <__imp__wfdopen>

externdef __imp__wfindfirst64:PANYARGS
vc__wfindfirst64 equ <__imp__wfindfirst64>

externdef __imp__wfindfirst:PANYARGS
vc__wfindfirst equ <__imp__wfindfirst>

externdef __imp__wfindfirsti64:PANYARGS
vc__wfindfirsti64 equ <__imp__wfindfirsti64>

externdef __imp__wfindnext64:PANYARGS
vc__wfindnext64 equ <__imp__wfindnext64>

externdef __imp__wfindnext:PANYARGS
vc__wfindnext equ <__imp__wfindnext>

externdef __imp__wfindnexti64:PANYARGS
vc__wfindnexti64 equ <__imp__wfindnexti64>

externdef __imp__wfopen:PANYARGS
vc__wfopen equ <__imp__wfopen>

externdef __imp__wfreopen:PANYARGS
vc__wfreopen equ <__imp__wfreopen>

externdef __imp__wfsopen:PANYARGS
vc__wfsopen equ <__imp__wfsopen>

externdef __imp__wfullpath:PANYARGS
vc__wfullpath equ <__imp__wfullpath>

externdef __imp__wgetcwd:PANYARGS
vc__wgetcwd equ <__imp__wgetcwd>

externdef __imp__wgetdcwd:PANYARGS
vc__wgetdcwd equ <__imp__wgetdcwd>

externdef __imp__wgetenv:PANYARGS
vc__wgetenv equ <__imp__wgetenv>

externdef __imp__winmajor:PANYARGS
vc__winmajor equ <__imp__winmajor>

externdef __imp__winminor:PANYARGS
vc__winminor equ <__imp__winminor>

externdef __imp__winver:PANYARGS
vc__winver equ <__imp__winver>

externdef __imp__wmakepath:PANYARGS
vc__wmakepath equ <__imp__wmakepath>

externdef __imp__wmkdir:PANYARGS
vc__wmkdir equ <__imp__wmkdir>

externdef __imp__wmktemp:PANYARGS
vc__wmktemp equ <__imp__wmktemp>

externdef __imp__wopen:PANYARGS
vc__wopen equ <__imp__wopen>

externdef __imp__wperror:PANYARGS
vc__wperror equ <__imp__wperror>

externdef __imp__wpgmptr:PANYARGS
vc__wpgmptr equ <__imp__wpgmptr>

externdef __imp__wpopen:PANYARGS
vc__wpopen equ <__imp__wpopen>

externdef __imp__wputenv:PANYARGS
vc__wputenv equ <__imp__wputenv>

externdef __imp__wremove:PANYARGS
vc__wremove equ <__imp__wremove>

externdef __imp__wrename:PANYARGS
vc__wrename equ <__imp__wrename>

externdef __imp__write:PANYARGS
vc__write equ <__imp__write>

externdef __imp__wrmdir:PANYARGS
vc__wrmdir equ <__imp__wrmdir>

externdef __imp__wsearchenv:PANYARGS
vc__wsearchenv equ <__imp__wsearchenv>

externdef __imp__wsetlocale:PANYARGS
vc__wsetlocale equ <__imp__wsetlocale>

externdef __imp__wsopen:PANYARGS
vc__wsopen equ <__imp__wsopen>

externdef __imp__wspawnl:PANYARGS
vc__wspawnl equ <__imp__wspawnl>

externdef __imp__wspawnle:PANYARGS
vc__wspawnle equ <__imp__wspawnle>

externdef __imp__wspawnlp:PANYARGS
vc__wspawnlp equ <__imp__wspawnlp>

externdef __imp__wspawnlpe:PANYARGS
vc__wspawnlpe equ <__imp__wspawnlpe>

externdef __imp__wspawnv:PANYARGS
vc__wspawnv equ <__imp__wspawnv>

externdef __imp__wspawnve:PANYARGS
vc__wspawnve equ <__imp__wspawnve>

externdef __imp__wspawnvp:PANYARGS
vc__wspawnvp equ <__imp__wspawnvp>

externdef __imp__wspawnvpe:PANYARGS
vc__wspawnvpe equ <__imp__wspawnvpe>

externdef __imp__wsplitpath:PANYARGS
vc__wsplitpath equ <__imp__wsplitpath>

externdef __imp__wstat64:PANYARGS
vc__wstat64 equ <__imp__wstat64>

externdef __imp__wstat:PANYARGS
vc__wstat equ <__imp__wstat>

externdef __imp__wstati64:PANYARGS
vc__wstati64 equ <__imp__wstati64>

externdef __imp__wstrdate:PANYARGS
vc__wstrdate equ <__imp__wstrdate>

externdef __imp__wstrtime:PANYARGS
vc__wstrtime equ <__imp__wstrtime>

externdef __imp__wsystem:PANYARGS
vc__wsystem equ <__imp__wsystem>

externdef __imp__wtempnam:PANYARGS
vc__wtempnam equ <__imp__wtempnam>

externdef __imp__wtmpnam:PANYARGS
vc__wtmpnam equ <__imp__wtmpnam>

externdef __imp__wtof:PANYARGS
vc__wtof equ <__imp__wtof>

externdef __imp__wtoi64:PANYARGS
vc__wtoi64 equ <__imp__wtoi64>

externdef __imp__wtoi:PANYARGS
vc__wtoi equ <__imp__wtoi>

externdef __imp__wtol:PANYARGS
vc__wtol equ <__imp__wtol>

externdef __imp__wunlink:PANYARGS
vc__wunlink equ <__imp__wunlink>

externdef __imp__wutime64:PANYARGS
vc__wutime64 equ <__imp__wutime64>

externdef __imp__wutime:PANYARGS
vc__wutime equ <__imp__wutime>

externdef __imp__y0:PANYARGS
vc__y0 equ <__imp__y0>

externdef __imp__y1:PANYARGS
vc__y1 equ <__imp__y1>

externdef __imp__yn:PANYARGS
vc__yn equ <__imp__yn>

externdef __imp_abort:PANYARGS
vc_abort equ <__imp_abort>

externdef __imp_abs:PANYARGS
vc_abs equ <__imp_abs>

externdef __imp_acos:PANYARGS
vc_acos equ <__imp_acos>

externdef __imp_acosf:PANYARGS
vc_acosf equ <__imp_acosf>

externdef __imp_asctime:PANYARGS
vc_asctime equ <__imp_asctime>

externdef __imp_asin:PANYARGS
vc_asin equ <__imp_asin>

externdef __imp_asinf:PANYARGS
vc_asinf equ <__imp_asinf>

externdef __imp_atan2:PANYARGS
vc_atan2 equ <__imp_atan2>

externdef __imp_atan2f:PANYARGS
vc_atan2f equ <__imp_atan2f>

externdef __imp_atan:PANYARGS
vc_atan equ <__imp_atan>

externdef __imp_atanf:PANYARGS
vc_atanf equ <__imp_atanf>

externdef __imp_atexit:PANYARGS
vc_atexit equ <__imp_atexit>

externdef __imp_atof:PANYARGS
vc_atof equ <__imp_atof>

externdef __imp_atoi:PANYARGS
vc_atoi equ <__imp_atoi>

externdef __imp_atol:PANYARGS
vc_atol equ <__imp_atol>

externdef __imp_bsearch:PANYARGS
vc_bsearch equ <__imp_bsearch>

externdef __imp_calloc:PANYARGS
vc_calloc equ <__imp_calloc>

externdef __imp_ceil:PANYARGS
vc_ceil equ <__imp_ceil>

externdef __imp_ceilf:PANYARGS
vc_ceilf equ <__imp_ceilf>

externdef __imp_clearerr:PANYARGS
vc_clearerr equ <__imp_clearerr>

externdef __imp_clock:PANYARGS
vc_clock equ <__imp_clock>

externdef __imp_cos:PANYARGS
vc_cos equ <__imp_cos>

externdef __imp_cosf:PANYARGS
vc_cosf equ <__imp_cosf>

externdef __imp_cosh:PANYARGS
vc_cosh equ <__imp_cosh>

externdef __imp_coshf:PANYARGS
vc_coshf equ <__imp_coshf>

externdef __imp_ctime:PANYARGS
vc_ctime equ <__imp_ctime>

externdef __imp_difftime:PANYARGS
vc_difftime equ <__imp_difftime>

externdef __imp_div:PANYARGS
vc_div equ <__imp_div>

externdef __imp_exit:PANYARGS
vc_exit equ <__imp_exit>

externdef __imp_exp:PANYARGS
vc_exp equ <__imp_exp>

externdef __imp_expf:PANYARGS
vc_expf equ <__imp_expf>

externdef __imp_fabs:PANYARGS
vc_fabs equ <__imp_fabs>

externdef __imp_fclose:PANYARGS
vc_fclose equ <__imp_fclose>

externdef __imp_feof:PANYARGS
vc_feof equ <__imp_feof>

externdef __imp_ferror:PANYARGS
vc_ferror equ <__imp_ferror>

externdef __imp_fflush:PANYARGS
vc_fflush equ <__imp_fflush>

externdef __imp_fgetc:PANYARGS
vc_fgetc equ <__imp_fgetc>

externdef __imp_fgetpos:PANYARGS
vc_fgetpos equ <__imp_fgetpos>

externdef __imp_fgets:PANYARGS
vc_fgets equ <__imp_fgets>

externdef __imp_fgetwc:PANYARGS
vc_fgetwc equ <__imp_fgetwc>

externdef __imp_fgetws:PANYARGS
vc_fgetws equ <__imp_fgetws>

externdef __imp_floor:PANYARGS
vc_floor equ <__imp_floor>

externdef __imp_floorf:PANYARGS
vc_floorf equ <__imp_floorf>

externdef __imp_fmod:PANYARGS
vc_fmod equ <__imp_fmod>

externdef __imp_fmodf:PANYARGS
vc_fmodf equ <__imp_fmodf>

externdef __imp_fopen:PANYARGS
vc_fopen equ <__imp_fopen>

externdef __imp_fprintf:PANYARGS
vc_fprintf equ <__imp_fprintf>

externdef __imp_fputc:PANYARGS
vc_fputc equ <__imp_fputc>

externdef __imp_fputs:PANYARGS
vc_fputs equ <__imp_fputs>

externdef __imp_fputwc:PANYARGS
vc_fputwc equ <__imp_fputwc>

externdef __imp_fputws:PANYARGS
vc_fputws equ <__imp_fputws>

externdef __imp_fread:PANYARGS
vc_fread equ <__imp_fread>

externdef __imp_free:PANYARGS
vc_free equ <__imp_free>

externdef __imp_freopen:PANYARGS
vc_freopen equ <__imp_freopen>

externdef __imp_frexp:PANYARGS
vc_frexp equ <__imp_frexp>

externdef __imp_fscanf:PANYARGS
vc_fscanf equ <__imp_fscanf>

externdef __imp_fseek:PANYARGS
vc_fseek equ <__imp_fseek>

externdef __imp_fsetpos:PANYARGS
vc_fsetpos equ <__imp_fsetpos>

externdef __imp_ftell:PANYARGS
vc_ftell equ <__imp_ftell>

externdef __imp_fwprintf:PANYARGS
vc_fwprintf equ <__imp_fwprintf>

externdef __imp_fwrite:PANYARGS
vc_fwrite equ <__imp_fwrite>

externdef __imp_fwscanf:PANYARGS
vc_fwscanf equ <__imp_fwscanf>

externdef __imp_getc:PANYARGS
vc_getc equ <__imp_getc>

externdef __imp_getchar:PANYARGS
vc_getchar equ <__imp_getchar>

externdef __imp_getenv:PANYARGS
vc_getenv equ <__imp_getenv>

externdef __imp_gets:PANYARGS
vc_gets equ <__imp_gets>

externdef __imp_getwc:PANYARGS
vc_getwc equ <__imp_getwc>

externdef __imp_getwchar:PANYARGS
vc_getwchar equ <__imp_getwchar>

externdef __imp_gmtime:PANYARGS
vc_gmtime equ <__imp_gmtime>

externdef __imp_is_wctype:PANYARGS
vc_is_wctype equ <__imp_is_wctype>

externdef __imp_isalnum:PANYARGS
vc_isalnum equ <__imp_isalnum>

externdef __imp_isalpha:PANYARGS
vc_isalpha equ <__imp_isalpha>

externdef __imp_iscntrl:PANYARGS
vc_iscntrl equ <__imp_iscntrl>

externdef __imp_isdigit:PANYARGS
vc_isdigit equ <__imp_isdigit>

externdef __imp_isgraph:PANYARGS
vc_isgraph equ <__imp_isgraph>

externdef __imp_isleadbyte:PANYARGS
vc_isleadbyte equ <__imp_isleadbyte>

externdef __imp_islower:PANYARGS
vc_islower equ <__imp_islower>

externdef __imp_isprint:PANYARGS
vc_isprint equ <__imp_isprint>

externdef __imp_ispunct:PANYARGS
vc_ispunct equ <__imp_ispunct>

externdef __imp_isspace:PANYARGS
vc_isspace equ <__imp_isspace>

externdef __imp_isupper:PANYARGS
vc_isupper equ <__imp_isupper>

externdef __imp_iswalnum:PANYARGS
vc_iswalnum equ <__imp_iswalnum>

externdef __imp_iswalpha:PANYARGS
vc_iswalpha equ <__imp_iswalpha>

externdef __imp_iswascii:PANYARGS
vc_iswascii equ <__imp_iswascii>

externdef __imp_iswcntrl:PANYARGS
vc_iswcntrl equ <__imp_iswcntrl>

externdef __imp_iswctype:PANYARGS
vc_iswctype equ <__imp_iswctype>

externdef __imp_iswdigit:PANYARGS
vc_iswdigit equ <__imp_iswdigit>

externdef __imp_iswgraph:PANYARGS
vc_iswgraph equ <__imp_iswgraph>

externdef __imp_iswlower:PANYARGS
vc_iswlower equ <__imp_iswlower>

externdef __imp_iswprint:PANYARGS
vc_iswprint equ <__imp_iswprint>

externdef __imp_iswpunct:PANYARGS
vc_iswpunct equ <__imp_iswpunct>

externdef __imp_iswspace:PANYARGS
vc_iswspace equ <__imp_iswspace>

externdef __imp_iswupper:PANYARGS
vc_iswupper equ <__imp_iswupper>

externdef __imp_iswxdigit:PANYARGS
vc_iswxdigit equ <__imp_iswxdigit>

externdef __imp_isxdigit:PANYARGS
vc_isxdigit equ <__imp_isxdigit>

externdef __imp_labs:PANYARGS
vc_labs equ <__imp_labs>

externdef __imp_ldexp:PANYARGS
vc_ldexp equ <__imp_ldexp>

externdef __imp_ldiv:PANYARGS
vc_ldiv equ <__imp_ldiv>

externdef __imp_localeconv:PANYARGS
vc_localeconv equ <__imp_localeconv>

externdef __imp_localtime:PANYARGS
vc_localtime equ <__imp_localtime>

externdef __imp_log10:PANYARGS
vc_log10 equ <__imp_log10>

externdef __imp_log10f:PANYARGS
vc_log10f equ <__imp_log10f>

externdef __imp_log:PANYARGS
vc_log equ <__imp_log>

externdef __imp_logf:PANYARGS
vc_logf equ <__imp_logf>

externdef __imp_longjmp:PANYARGS
vc_longjmp equ <__imp_longjmp>

externdef __imp_malloc:PANYARGS
vc_malloc equ <__imp_malloc>

externdef __imp_mblen:PANYARGS
vc_mblen equ <__imp_mblen>

externdef __imp_mbstowcs:PANYARGS
vc_mbstowcs equ <__imp_mbstowcs>

externdef __imp_mbtowc:PANYARGS
vc_mbtowc equ <__imp_mbtowc>

externdef __imp_memchr:PANYARGS
vc_memchr equ <__imp_memchr>

externdef __imp_memcmp:PANYARGS
vc_memcmp equ <__imp_memcmp>

externdef __imp_memcpy:PANYARGS
vc_memcpy equ <__imp_memcpy>

externdef __imp_memmove:PANYARGS
vc_memmove equ <__imp_memmove>

externdef __imp_memset:PANYARGS
vc_memset equ <__imp_memset>

externdef __imp_mktime:PANYARGS
vc_mktime equ <__imp_mktime>

externdef __imp_modf:PANYARGS
vc_modf equ <__imp_modf>

externdef __imp_modff:PANYARGS
vc_modff equ <__imp_modff>

externdef __imp_perror:PANYARGS
vc_perror equ <__imp_perror>

externdef __imp_pow:PANYARGS
vc_pow equ <__imp_pow>

externdef __imp_powf:PANYARGS
vc_powf equ <__imp_powf>

externdef __imp_printf:PANYARGS
vc_printf equ <__imp_printf>

externdef __imp_putc:PANYARGS
vc_putc equ <__imp_putc>

externdef __imp_putchar:PANYARGS
vc_putchar equ <__imp_putchar>

externdef __imp_puts:PANYARGS
vc_puts equ <__imp_puts>

externdef __imp_putwc:PANYARGS
vc_putwc equ <__imp_putwc>

externdef __imp_putwchar:PANYARGS
vc_putwchar equ <__imp_putwchar>

externdef __imp_qsort:PANYARGS
vc_qsort equ <__imp_qsort>

externdef __imp_raise:PANYARGS
vc_raise equ <__imp_raise>

externdef __imp_rand:PANYARGS
vc_rand equ <__imp_rand>

externdef __imp_realloc:PANYARGS
vc_realloc equ <__imp_realloc>

externdef __imp_remove:PANYARGS
vc_remove equ <__imp_remove>

externdef __imp_rename:PANYARGS
vc_rename equ <__imp_rename>

externdef __imp_rewind:PANYARGS
vc_rewind equ <__imp_rewind>

externdef __imp_scanf:PANYARGS
vc_scanf equ <__imp_scanf>

externdef __imp_setbuf:PANYARGS
vc_setbuf equ <__imp_setbuf>

externdef __imp_setjmp:PANYARGS
vc_setjmp equ <__imp_setjmp>

externdef __imp_setlocale:PANYARGS
vc_setlocale equ <__imp_setlocale>

externdef __imp_setvbuf:PANYARGS
vc_setvbuf equ <__imp_setvbuf>

externdef __imp_signal:PANYARGS
vc_signal equ <__imp_signal>

externdef __imp_sin:PANYARGS
vc_sin equ <__imp_sin>

externdef __imp_sinf:PANYARGS
vc_sinf equ <__imp_sinf>

externdef __imp_sinh:PANYARGS
vc_sinh equ <__imp_sinh>

externdef __imp_sinhf:PANYARGS
vc_sinhf equ <__imp_sinhf>

externdef __imp_sprintf:PANYARGS
vc_sprintf equ <__imp_sprintf>

externdef __imp_sqrt:PANYARGS
vc_sqrt equ <__imp_sqrt>

externdef __imp_sqrtf:PANYARGS
vc_sqrtf equ <__imp_sqrtf>

externdef __imp_srand:PANYARGS
vc_srand equ <__imp_srand>

externdef __imp_sscanf:PANYARGS
vc_sscanf equ <__imp_sscanf>

externdef __imp_strcat:PANYARGS
vc_strcat equ <__imp_strcat>

externdef __imp_strchr:PANYARGS
vc_strchr equ <__imp_strchr>

externdef __imp_strcmp:PANYARGS
vc_strcmp equ <__imp_strcmp>

externdef __imp_strcoll:PANYARGS
vc_strcoll equ <__imp_strcoll>

externdef __imp_strcpy:PANYARGS
vc_strcpy equ <__imp_strcpy>

externdef __imp_strcspn:PANYARGS
vc_strcspn equ <__imp_strcspn>

externdef __imp_strerror:PANYARGS
vc_strerror equ <__imp_strerror>

externdef __imp_strftime:PANYARGS
vc_strftime equ <__imp_strftime>

externdef __imp_strlen:PANYARGS
vc_strlen equ <__imp_strlen>

externdef __imp_strncat:PANYARGS
vc_strncat equ <__imp_strncat>

externdef __imp_strncmp:PANYARGS
vc_strncmp equ <__imp_strncmp>

externdef __imp_strncpy:PANYARGS
vc_strncpy equ <__imp_strncpy>

externdef __imp_strpbrk:PANYARGS
vc_strpbrk equ <__imp_strpbrk>

externdef __imp_strrchr:PANYARGS
vc_strrchr equ <__imp_strrchr>

externdef __imp_strspn:PANYARGS
vc_strspn equ <__imp_strspn>

externdef __imp_strstr:PANYARGS
vc_strstr equ <__imp_strstr>

externdef __imp_strtod:PANYARGS
vc_strtod equ <__imp_strtod>

externdef __imp_strtok:PANYARGS
vc_strtok equ <__imp_strtok>

externdef __imp_strtol:PANYARGS
vc_strtol equ <__imp_strtol>

externdef __imp_strtoul:PANYARGS
vc_strtoul equ <__imp_strtoul>

externdef __imp_strxfrm:PANYARGS
vc_strxfrm equ <__imp_strxfrm>

externdef __imp_swprintf:PANYARGS
vc_swprintf equ <__imp_swprintf>

externdef __imp_swscanf:PANYARGS
vc_swscanf equ <__imp_swscanf>

externdef __imp_system:PANYARGS
vc_system equ <__imp_system>

externdef __imp_tan:PANYARGS
vc_tan equ <__imp_tan>

externdef __imp_tanf:PANYARGS
vc_tanf equ <__imp_tanf>

externdef __imp_tanh:PANYARGS
vc_tanh equ <__imp_tanh>

externdef __imp_time:PANYARGS
vc_time equ <__imp_time>

externdef __imp_tmpfile:PANYARGS
vc_tmpfile equ <__imp_tmpfile>

externdef __imp_tmpnam:PANYARGS
vc_tmpnam equ <__imp_tmpnam>

externdef __imp_tolower:PANYARGS
vc_tolower equ <__imp_tolower>

externdef __imp_toupper:PANYARGS
vc_toupper equ <__imp_toupper>

externdef __imp_towlower:PANYARGS
vc_towlower equ <__imp_towlower>

externdef __imp_towupper:PANYARGS
vc_towupper equ <__imp_towupper>

externdef __imp_ungetc:PANYARGS
vc_ungetc equ <__imp_ungetc>

externdef __imp_ungetwc:PANYARGS
vc_ungetwc equ <__imp_ungetwc>

externdef __imp_vfprintf:PANYARGS
vc_vfprintf equ <__imp_vfprintf>

externdef __imp_vfwprintf:PANYARGS
vc_vfwprintf equ <__imp_vfwprintf>

externdef __imp_vprintf:PANYARGS
vc_vprintf equ <__imp_vprintf>

externdef __imp_vsprintf:PANYARGS
vc_vsprintf equ <__imp_vsprintf>

externdef __imp_vswprintf:PANYARGS
vc_vswprintf equ <__imp_vswprintf>

externdef __imp_vwprintf:PANYARGS
vc_vwprintf equ <__imp_vwprintf>

externdef __imp_wcscat:PANYARGS
vc_wcscat equ <__imp_wcscat>

externdef __imp_wcschr:PANYARGS
vc_wcschr equ <__imp_wcschr>

externdef __imp_wcscmp:PANYARGS
vc_wcscmp equ <__imp_wcscmp>

externdef __imp_wcscoll:PANYARGS
vc_wcscoll equ <__imp_wcscoll>

externdef __imp_wcscpy:PANYARGS
vc_wcscpy equ <__imp_wcscpy>

externdef __imp_wcscspn:PANYARGS
vc_wcscspn equ <__imp_wcscspn>

externdef __imp_wcsftime:PANYARGS
vc_wcsftime equ <__imp_wcsftime>

externdef __imp_wcslen:PANYARGS
vc_wcslen equ <__imp_wcslen>

externdef __imp_wcsncat:PANYARGS
vc_wcsncat equ <__imp_wcsncat>

externdef __imp_wcsncmp:PANYARGS
vc_wcsncmp equ <__imp_wcsncmp>

externdef __imp_wcsncpy:PANYARGS
vc_wcsncpy equ <__imp_wcsncpy>

externdef __imp_wcspbrk:PANYARGS
vc_wcspbrk equ <__imp_wcspbrk>

externdef __imp_wcsrchr:PANYARGS
vc_wcsrchr equ <__imp_wcsrchr>

externdef __imp_wcsspn:PANYARGS
vc_wcsspn equ <__imp_wcsspn>

externdef __imp_wcsstr:PANYARGS
vc_wcsstr equ <__imp_wcsstr>

externdef __imp_wcstod:PANYARGS
vc_wcstod equ <__imp_wcstod>

externdef __imp_wcstok:PANYARGS
vc_wcstok equ <__imp_wcstok>

externdef __imp_wcstol:PANYARGS
vc_wcstol equ <__imp_wcstol>

externdef __imp_wcstombs:PANYARGS
vc_wcstombs equ <__imp_wcstombs>

externdef __imp_wcstoul:PANYARGS
vc_wcstoul equ <__imp_wcstoul>

externdef __imp_wcsxfrm:PANYARGS
vc_wcsxfrm equ <__imp_wcsxfrm>

externdef __imp_wctomb:PANYARGS
vc_wctomb equ <__imp_wctomb>

externdef __imp_wprintf:PANYARGS
vc_wprintf equ <__imp_wprintf>

externdef __imp_wscanf:PANYARGS
vc_wscanf equ <__imp_wscanf>
